spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database01?serverTimezone=UTC
    username: root
    password: 1116
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

    #hibernate:
      #ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表

server:
  port: 8181
